name: dart_webcore_new
description: A new way for Dart into the web server world.
version: 0.3.1
homepage: https://github.com/amrmhassan/dart_webcore

environment:
    sdk: '>=2.19.6 <4.0.0'

dependencies:
  logger: ^1.3.0
  mime: ^1.0.4
  path: ^1.8.2
  uuid: ^3.0.7

dev_dependencies:
  dart_style: ^2.0.0

